[package]
name = "cryptolixir_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "cryptolixir_native"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.1"
sha = "0.10"
digest = "0.9"
